name: terraform_ci_cd
on: push

jobs:
  Unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: python3 -m pip install --upgrade pip && pip3 install pytest && pip3 install boto3 && pip3 install moto[dynamodb2]

      - name: Test get and put functions
        run: cd modules/back-end && pytest test_table.py -v
  
  Terraform-plan:
    needs: Unit-test
    runs-on: ubuntu-latest
     
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: eu-west-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init
        id: init
        run: cd runtime && terraform init

      - name: Terraform plan
        id: plan
        run: cd runtime && terraform plan -no-color
        continue-on-error: true

  Terraform-apply:
    needs: [Unit-test, Terraform-plan]
    environment: Manual approval
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: eu-west-2
 
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init
        id: init
        run: cd runtime && terraform init

      - name: Terraform apply
        id: apply
        run: cd runtime && terraform apply -auto-approve

Terraform-apply-remote-tf-state:
    needs: [Terraform-apply]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: eu-west-2
 
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform init
        id: init
        run: cd remote_tf_state && terraform init

      - name: Terraform apply
        id: apply
        run: cd remote_tf_state && terraform apply -auto-approve